version: 2
jobs:
  build:
    working_directory: /tmp/firehose-writer
    docker:
      - image: node:9
    steps:
      - checkout
      - restore_cache:
          key: firehose-writer-{{ checksum "package.json" }}
      - run: npm install
      - type: shell
        command: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter \
          && chmod +x ./cc-test-reporter \
          && ./cc-test-reporter before-build \
          && node_modules/nyc/bin/nyc.js --reporter=lcov npm test \
          && ./cc-test-reporter after-build --exit-code $?
        environment:
          CC_TEST_REPORTER_ID: 4e26a000a825bf523a9d3583b19b6ae5c430f5f6ea56eafbd9b6592782b1e10e
      - save_cache:
          key: firehose-writer-{{ checksum "package.json" }}
          paths:
            - node_modules
      - store_artifacts:
          path: /tmp/firehose-writer/coverage/lcov-report
          destination: coverage
  publish:
    docker:
      - image: node:9
    steps:
      - publish:
          name: Publish package to NPM
          command: npm publish
workflows:
  version: 2
  ci:
    jobs:
      - build
      - publish:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires: build

